---
version: 2.5.0.0-rc43
homeassistant: 2022.6.1
slug: mariadb-beta
name: "[BETA] In-memory MariaDB"
description: "[BETA] An in-memory SQL database server"
url: https://github.com/lmagyar/homeassistant-addon-mariadb-inmemory
codenotary: lmagyar1973@gmail.com
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
tmpfs: true
privileged:
  - SYS_ADMIN
map:
  - share:rw
backup_pre: /command/s6-svc -wu -u /run/service/mariadb-backup/
backup_post: /command/s6-svc -wd -d /run/service/mariadb-backup/
image: lmagyar/{arch}-addon-mariadb-inmemory
init: false
options:
  tmpfs:
    size: 200m
  retention:
    enabled: true
  databases:
    - homeassistant
  logins:
    - password: null
      username: homeassistant
  rights:
    - database: homeassistant
      username: homeassistant
ports:
  3306/tcp:
schema:
  tmpfs:
    size: match(^\d+[kmg]?$)
  retention:
    enabled: bool
  databases:
    - str
  logins:
    - username: str
      password: password
  rights:
    - database: str
      privileges:
        - "list(ALTER|CREATE|CREATE ROUTINE|CREATE TEMPORARY TABLES|\
           CREATE VIEW|DELETE|DELETE HISTORY|DROP|EVENT|GRANT OPTION|INDEX|\
           INSERT|LOCK TABLES|SELECT|SHOW VIEW|TRIGGER|UPDATE)?"
      username: str
services:
  - mysql:provide
startup: system
timeout: 60

